server:
  port: 9999

spring:
  application:
    name: @pom.artifactId@

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      #defaultZone: ${EUREKA_SERVICE_URL:http://localhost:9000}/eureka
      defaultZone: http://39.108.101.181:9000/eureka
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
    #instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#spring
#  boot
#    admin
#      context-path: /
